Repository discordplace/lantern, pull requests merged in 2024-08, with the labels that each got.

#4 Key value storage
  README.md
  server/config.toml
  server/lib/bot/commands/kv/storage.js
  server/lib/bot/events/interactionCreate.js
  server/lib/express/middlewares/validateRequest.js
  server/lib/express/routes/api/v1/users/[user_id]/createSvg.js
  server/lib/express/routes/api/v1/users/[user_id]/index.js
  server/lib/express/routes/api/v1/users/[user_id]/storage/[key].js
  server/lib/express/routes/api/v1/users/[user_id]/storage/index.js
  server/lib/models/Storage.js
  server/lib/utils/encryption.js
  server/lib/utils/getValidationError.js
  server/package.json
  server/pnpm-lock.yaml
Labels: Backend: Feature

#5 Bulk get users
  README.md
  server/config.toml
  server/lib/express/routes/api/v1/users/index.js
Labels: Backend: Feature

#6 New eslint rule
  server/.eslintrc.js
  server/lib/express/routes/socket/index.js
  server/lib/utils/createUserData.js
Labels: Backend: Feature

#7 Added CORS support
  server/lib/express/createServer.js
Labels: Backend: Security

#8 Added XSS protection
  server/lib/express/routes/api/v1/users/[user_id]/createSvg.js
  server/package.json
  server/pnpm-lock.yaml
Labels: Backend: Bug, Backend: Security
