Repository discordplace/lantern, pull requests merged in 2024-09, with the labels that each got.

#10 Correctly handle simultaneous requests
  server/lib/express/createServer.js
  server/lib/express/middlewares/handleSimultaneousRequests.js
  server/package.json
  server/pnpm-lock.yaml
Labels: Backend: Security

#11 Refactor github_auto_deploy route
  .github/labels.yml
  README.md
  server/lib/express/routes/api/v1/github_auto_deploy.js
  server/package.json
  server/pnpm-lock.yaml
Labels: Backend: Feature

#12 WebSocket Improvements
  README.md
  server/config.toml
  server/lib/express/routes/socket/index.js
Labels: Backend: Feature, Backend: Security

#13 SVG Update
  README.md
  server/lib/express/routes/api/v1/users/[user_id]/createSvg.js
  server/lib/express/routes/api/v1/users/[user_id]/index.js
  server/package-lock.json
  server/package.json
Labels: Backend: Feature
